# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    identifier: Home
  - name: About
    url: '#about'
    weight: 11
    parent: Home
  - name: "About the data observatories"
    url: ../about/observatories
    weight: 12
    parent: Home
  - name: "In 1 minute: slide introduction"
    url: '#slider'
    weight: 13
    parent: Home
  - name: News
    weight: 20
    identifier: News
  - name: Blog
    url: '#posts'
    weight: 21
    parent: News
  - name: Topics
    url: '#tags'
    weight: 22
    parent: News
  - name: Solutions
    url: '#services'
    weight: 30
    identifier: Solutions
  - name: Apps
    url: 'apps/'
    weight: 31
    parent: Solutions
  - name: Software
    url: '#releases'
    weight: 32
    parent: Solutions
#  - name: Use cases
#    url: '#usecase'
#    weight: 34
    parent: Solutions
  - name: Code
    url: '/category/r-bloggers/'
    weight: 34
    parent: Solutions
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: ğŸ›ï¸ Economy
    url: '#pillars'
    weight: 41
    parent: Data
  - name: ğŸ›ï¸ Diversity & Circulation
    url: '#pillars'
    weight: 42
    parent: Data
  - name: ğŸ›ï¸ Cultre &  Society
    url: '#pillars'
    weight: 43
    parent: Data
  - name: ğŸ›ï¸ Art+Tech
    url: '#pillars'
    weight: 44
    parent: Data
  - name: ğŸ“– Open Science Repository
    url: 'https://zenodo.org/communities/ccsi/'
    weight: 45
    parent: Data
  - name: ğŸ™ï¸ Open Music Collections
    url: https://www.opencollections.net/collections/music/
    weight: 46
    parent: Data
  - name: ğŸï¸ Open Photography Collections
    url: https://www.opencollections.net/collections/photography/
    weight: 47
    parent: Data
  - name: ğŸ–¼ï¸ Open Prints Collections
    url: https://www.opencollections.net/collections/print/
    weight: 48
    parent: Data
  - name: ğŸ–¥ï¸ API
    url: '#data'
    weight: 49
    parent: Data
  - name: Projects
    url: '#projects'
    weight: 50
    identifier: Projects
  - name: Overview
    url: '#projects'
    weight: 51
    parent: Projects
  - name: ğŸ‡ªğŸ‡º Listen Local
    url: '/project/listen-local/'
    weight: 52
    parent: Projects
  - name: ğŸ‡ªğŸ‡º Opem Music Observatory - OpenMuse
    url: '/project/openmuse/'
    weight: 53
    parent: Projects
  - name: RECREO
    url: '#projects'
    weight: 54
    parent: Projects
  - name: Call for Interest
    url: "../project/horizon"
    weight: 55
    parent: Projects
  - name: Publications
    url: '#featured'
    weight: 60
    identifier: Publications
  - name: Featured
    url: '#featured'
    weight: 60
    parent: Publications
  - name: All Publications
    url: '#publications'
    weight: 62
    parent: Publications
  - name: Partners
    url: "#partners"
    weight: 70
    identifier: Partners
  - name: Observatory Partners
    url: '#partners'
    weight: 71
    parent: Partners
  - name: Call for Research Interest
    url: "../project/horizon"
    weight: 72
    parent: Partners
  - name: Contact
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '#contact'
    weight: 91
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact
  - name: Meetups in Europe
    url: '/category/meetup/'
    weight: 93
    parent: Contact

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
